### ISSUE TITLE
UI : Alert button to warn the cozy team when a connector is not working

### ISSUE THREAD

**Issue by RichardFevrier** [cozy/cozy-store#687]
I added a connector (Probikeshop) to test and it is not fetching my receipt from 2018.
So I was wondering how I could warn your team and I couldn't find any easy way except maybe contact your support by mail.
Maybe a button like "Report an issue" on the app detail panel on the home and the store could be a solution. Only if the user is properly logged in of course.

**Comment by Crash--** [comment]
Hey @RichardFevrier, 

Thanks for taking the time to report an issue. You can contact the support by email to report this kind of issue, or you can use the repo of the Probikeshop's konnector to report it. (https://github.com/konnectors/probikeshop).

We're thinking about that kind of button to send us a report with your attached log to be able to debug 

I'm the owner of this konnector, and since a few weeks (months?) they have changed the way they handle the login process and there is some track of API now. 

(I created an issue here https://github.com/konnectors/probikeshop/issues/257)

**Comment by RichardFevrier** [comment]
Thank you for your answer @Crash-- ,

Probikeshop here was only an example, I can edit the Issue if you want.

The real point here is in the title of this issue and it is to report a problem with a konnector in an easy/fast way.

Only 1 out of 4 konnectors I've tried so far was working and even then not perfectly.
I'm not blaming you, I know it's clearly not your fault, it's not just like consuming APIs.

But as a client I was not sure you were aware of those problems (because they are not in a "maintenance" status and installable) and I was looking for a way to share this information.

So if you are also thinking about that kind of button with a report attached, I think it would be a good idea to keep this issue open until a good solution is implemented. What do you think ? :)

**Comment by Crash--** [comment]
We don't keep issue open for feature request ;). You can send a mail to our support or open a discussion on our forum (https://forum.cozy.io/)
